version: "3"

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    restart: always

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
