version: '3'

services:
  beginners_rop:
    build:
      context: .
    restart: always
    working_dir:  /home/pwn
    container_name: beginners_rop 
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "4102:4102"
    entrypoint: /etc/init.sh
