version: "3"

services:
  uwsgi:
    build: ./app
    volumes:
      - ./app:/var/www/
    env_file: .env
    environment:
      TZ: "Asia/Tokyo"
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - uwsgi
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"